version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ampliar_postgres
    restart: always
    environment:
      POSTGRES_USER: ampliardb
      POSTGRES_PASSWORD: ampliardb
      POSTGRES_DB: ampliar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: